all:
	gcc -o elimina-par elimina-par.c stack.c
	gcc -o maze maze.c pstack.c
	gcc -o maze2 maze2.c pstack.c
	gcc -o maze_animated maze_animated.c pstack.c
	gcc -o parser parser.c stack.c
	gcc -o polish polish.c stack.c
	gcc -o polish_solver polish_solver.c stack.c
	gcc -o palindrome palindrome.c stack.c
	gcc -o prime_factorization prime_factorization.c stack.c
	gcc -o reverse reverse.c stack.c queue.c
	gcc -o game game.c stack.c
	gcc -o minesweeper minesweeper.c pstack.c
	gcc -o minesweeper2 minesweeper2.c pstack.c
clean:
	rm elimina-par maze parser polish reverse minesweeper

