all:
	gcc -o par_impar par_impar.c queue.c
	gcc -o islands islands.c pqueue.c
	gcc -o islands2 islands2.c pqueue.c
	gcc -o imagens imagens.c pqueue.c
	gcc -o jackpot jackpot.c queue.c
	gcc -o jackpot2 jackpot2.c queue.c
	gcc -o merge merge.c queue.c
	gcc -o merge2 merge2.c queue.c
	gcc -o merge3 merge3.c queue.c
	gcc -o reverse reverse.c queue.c
	gcc -o reverse2 reverse2.c queue.c
	gcc -o josephus josephus.c queue.c
	gcc -o josephus2 josephus2.c queue.c
	gcc -o pagefault pagefault.c queue.c 
	gcc -o round-robin round-robin.c queue.c
	gcc -o round-robin2 round-robin2.c queue.c
	gcc -o round-robin3 round-robin3.c dqueue.c
clean:
	rm par_impar islands imagens jackpot
