all:
	gcc -o par_impar par_impar.c queue.c
	gcc -o islands islands.c pqueue.c
	gcc -o imagens imagens.c pqueue.c
	gcc -o jackpot jackpot.c queue.c
	gcc -o jackpot2 jackpot2.c queue.c
	gcc -o merge merge.c queue.c
clean:
	rm par_impar islands imagens jackpot
